spring.application.name=todo
spring.datasource.url=jdbc:postgresql://ENDEREÇO/coltodo
spring.datasource.username=USUARIO
spring.datasource.password=SENHA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration